### ISSUE TITLE
[BUG] Dependencies are being fetched from eBay Corp proxy

### ISSUE THREAD

**Issue by 6220119** [eBay/figma-include-accessibility-annotations#30]
### Details

Rather than the public npm package registry, (most) node_modules dependencies are being fetched from `artifactory.corp.ebay.com` on `npm install`. This is not expected.

Linkage from `artifactory.corp.ebay.com` started appearing since commit https://github.com/eBay/figma-include-accessibility-annotations/commit/7734edb7aa6bdfd1250775ffa12d1f8b82d9452e

### Expected Behavior

On `npm install`, dependencies should be fetched from a publicly accessible registry (i.e. `registry.npmjs.org`), at least, for the public audience/contributors that wants to contribute to this repository.

### Actual Behavior

Got network errors when fetching dependencies.

```sh
npm ERR! code ENOTFOUND
npm ERR! syscall getaddrinfo
npm ERR! errno ENOTFOUND
npm ERR! network request to https://artifactory.corp.ebay.com/artifactory/api/npm/npm-corp/stylelint-scss/-/stylelint-scss-5.3.1.tgz failed, reason: getaddrinfo ENOTFOUND artifactory.corp.ebay.com
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

```

<details><summary>Additional Info</summary>

### Your Environment

- macOS
- Node v20

### Steps to Reproduce

1. Connect to any public network
2. Pull the repo
3. `npm install`
4. Observe errors telling you dependencies cannot be fetched from eBay Artifactory.

### Stack Trace

```sh
npm ERR! code ENOTFOUND
npm ERR! syscall getaddrinfo
npm ERR! errno ENOTFOUND
npm ERR! network request to https://artifactory.corp.ebay.com/artifactory/api/npm/npm-corp/stylelint-scss/-/stylelint-scss-5.3.1.tgz failed, reason: getaddrinfo ENOTFOUND artifactory.corp.ebay.com
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

```
</details>

**Comment by megan-woodruff** [comment]
Thanks for reporting! Looking into this now
